### ISSUE TITLE
command 'build' has no such option 'i18n'

### ISSUE THREAD

**Issue by Antwnina** [tualatrix/ubuntu-tweak#36]
~/Downloads/ubuntu-tweak-master$ sudo python setup.py install
running install
error: error in setup.cfg: command 'build' has no such option 'i18n'

**Comment by andruo** [comment]
The issue solved in https://answers.launchpad.net/ubuntu-tweak/+question/170755

**Comment by fastenedrex** [comment]
This did not solve the problem for me. I receive errors when I run the program

**Comment by purefan** [comment]
This project is no longer under maintenance, Im not sure if that includes not accepting pull requests but I would not have my hopes up for having this issue fixed
